erf.registration_type.*:
  type: config_entity
  label: 'Registration type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    handlers:
      type: sequence
      label: 'Handlers'
      sequence:
        type: string
    uuid:
      type: string
