<?php

/**
 * @file
 * Contains commerce_order_item_render_widget.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_order_item_render_widget_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_order_item_render_widget module.
    case 'help.page.commerce_order_item_render_widget':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Includes an Order Item Purchased Entity widget that displays a rendered variation in a radio button list.') . '</p>';
      return $output;

    default:
  }
}
