# This file contains a few entries for testing parts of the API. It's meant to be used with https://marketplace.visualstudio.com/items?itemName=humao.rest-client

POST http://registrations.ilr.test/hooks/v1/salesforce-commerce HTTP/1.1
content-type: application/json

{
  "sf_order_id": "a0M3J000000GUUgUAO",
  "pos_order_id": 122
}
