# config/schema/commerce_freedompay.schema.yml
commerce_payment.commerce_payment_gateway.plugin.freedompay_hpp:
  type: commerce_payment_gateway_configuration
  mapping:
    store_id:
      type: string
      label: 'Store ID'
    terminal_id:
      type: string
      label: 'Terminal ID'
