<?php

/**
 * @file
 * Contains ilr_groat.module.
 */

use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Custom allowed_values_function callback for the participant class year field.
 *
 * @see callback_allowed_values_function().
 */
function ilr_groat_class_year_options(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity, &$cacheable) {
  $years = range((int) date('Y'), 1947);
  return array_combine($years, $years);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter the registration entity form for the type `groat_alpern_awards`.
 *
 * - Updates the register button text for clarity.
 */
function ilr_registrations_form_registration_groat_alpern_awards_embedded_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_state->getFormObject()->getEntity()->isNew()) {
    $button_text = t('Add to cart');
  }
  else {
    $button_text = t('Update cart');
  }

  $form['actions']['submit']['#value'] = $button_text;
}
