<?php

/**
 * @file
 * Contains ilr_groat.module.
 */

use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Entity\FieldableEntityInterface;

/**
 * Custom allowed_values_function callback for the participant class year field.
 *
 * @see callback_allowed_values_function().
 */
function ilr_groat_class_year_options(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity, &$cacheable) {
  $years = range((int) date('Y'), 1947);
  return array_combine($years, $years);
}
